### ISSUE TITLE
Resolving dependencies inside dependencies

### ISSUE THREAD

**Issue by thetutlage** [lpiepiora/bower-webpack-plugin#12]
I am using angular js , and a module i try http://likeastore.github.io/ngDialog/ also requiring angular.js and is getting failed.

`require('angular')` inside ngDialog is looking for angular inside node_modules instead of bower_components

**Comment by cmartin81** [comment]
I have the same problem. When I try to import a bower component which has other dependencies it failes :(

In my case I am trying to import ng-switchery which is dependent on switchery which has 2 dependencies ( fastclick and transitionize)

**Comment by cmartin81** [comment]
@thetutlage did you find a solution?

**Comment by thetutlage** [comment]
No , not so far

**Comment by weslien** [comment]
+1 for this, we are having to fall back to adding all child dependencies in parent bower.json.
Ugly solution - automatically resolving transitive dependencies would be much nicer.

**Comment by forres** [comment]
Any solutions? 
I'm trying to solve the same

**Comment by thetutlage** [comment]
try to stick to npm now , i have seen lot of respositories are moving to npm even angular made official 1.4 launch with npm

it better to stay with the eco system

**Comment by nilssolanki** [comment]
I have the same issue when trying to use select2 (https://github.com/select2/select2). On NPM, it is still version 3.5.2, whereas on bower it is already the new 4.0.0 version. But if I try to load the bower module via webpack, it also tries to resolve the requires in the webpack root instead of the bower package itself.
Are there any solutions to this yet?

**Comment by julianSelser** [comment]
+1
